#!/bin/bash

find $1 -maxdepth 1 -type f -name '*' | while read FILE ; do
	newfile="$(echo ${FILE} |sed -e 's/ ... BluRay1080p ! 2015//')" ;
	newfile="$(echo ${newfile} |sed -e 's/ ... BluRay1080p ! 2016//')" ;
	newfile="$(echo ${newfile} |sed -e 's/ ... WebDl1080p ! 2017/ WEB-DL 1080p/')" ;
	newfile="$(echo ${newfile} |sed -e 's/ ... WebDl1080p ! 2018/ WEB-DL 1080p/')" ;
	newfile="$(echo ${newfile} |sed -e 's/FHD_6M-//')" ;
	newfile="$(echo ${newfile} |sed -e 's/\[FHD6m\]//')" ;
	newfile="$(echo ${newfile} |sed -e 's/\[FHD\]//')" ;
	newfile="$(echo ${newfile} |sed -e 's/.1080p././')" ;
	newfile="$(echo ${newfile} |sed -e 's/.1080P././')" ;
	newfile="$(echo ${newfile} |sed -e 's/.HD././')" ;
	newfile="$(echo ${newfile} |sed -e 's/\FHD-//')" ;
	newfile="$(echo ${newfile} |sed -e 's/\hd_//')" ;
	[[ ${FILE} != ${newfile} ]] && mv "${FILE}" "${newfile}" ;
done 
